# Generated by Django 5.0.7 on 2024-08-09 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='travello.destination'),
        ),
    ]
